apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudit
  namespace: cloudit
  labels:
    app: cloudit
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1


  selector:
    matchLabels:
      app: cloudit
  template:
    metadata:
      labels:
        app: cloudit
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: cloudit
          image: cloudit-frontend:v2
          imagePullPolicy: Never
          envFrom:
          - configMapRef:
              name: cloudit-config
          - secretRef:
              name: cloudit-secret
          ports:
            - containerPort: 80


          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 10
      

          startupProbe:
              httpGet:
                path: /operations.html
                port: 80
              periodSeconds: 5
              failureThreshold: 12
              timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: /operations.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          
          livenessProbe:
            httpGet:
              path: /operations.html
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"