apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cloudit
  labels:
    app: postgres
    component: database
type: Opaque
stringData:
  POSTGRES_DB: clouditdb
  POSTGRES_USER: replace-with-database-user
  POSTGRES_PASSWORD: replace-with-strong-password