FROM nginx:1.27-alpine

COPY nginx.fullstack.conf /etc/nginx/conf.d/default.conf

COPY index.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/style.css
COPY script.js /usr/share/nginx/html/script.js

COPY operations.html /usr/share/nginx/html/operations.html
COPY operations.css /usr/share/nginx/html/operations.css
COPY operations.js /usr/share/nginx/html/operations.js

EXPOSE 80

HEALTHCHECK --interval=10s --timeout=3s --start-period=15s --retries=3 \
CMD wget -q -O /dev/null http://127.0.0.1/operations.html || exit 1